INSERT INTO movies (title, description, release_date, director, actors, genres)
VALUES
    ('Star Wars: Episode I - The Phantom Menace', 'Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.', '1999-05-19', 'George Lucas', '{Liam Neeson,Ewan McGregor,Natalie Portman,Jake Lloyd,Ian McDiarmid,Ahmed Best,Pernilla August}', '{Sci-Fi,Action,Adventure}'),

    ('Star Wars: Episode II - Attack of the Clones', 'Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé Amidala, while Obi-Wan Kenobi investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi.', '2002-05-16', 'George Lucas', '{Ewan McGregor,Natalie Portman,Hayden Christensen,Christopher Lee,Samuel L. Jackson,Frank Oz,Ian McDiarmid,Temuera Morrison}', '{Sci-Fi,Action,Adventure,Romance}'),

    ('Star Wars: Episode III - Revenge of the Sith', 'Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.', '2005-05-19', 'George Lucas', '{Ewan McGregor,Natalie Portman,Hayden Christensen,Ian McDiarmid,Samuel L. Jackson,Christopher Lee,Frank Oz,Jimmy Smits}', '{Sci-Fi,Action,Adventure,Drama}'),

    ('Star Wars: Episode IV - A New Hope', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire''s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.', '1977-05-25', 'George Lucas', '{Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,Peter Cushing,Anthony Daniels,Kenny Baker,Peter Mayhew,David Prowse}', '{Sci-Fi,Action,Adventure,Fantasy}'),

    ('Star Wars: Episode V - The Empire Strikes Back', 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.', '1980-05-21', 'Irvin Kershner', '{Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Anthony Daniels,Peter Mayhew,Frank Oz,Alec Guinness,David Prowse,James Earl Jones}', '{Sci-Fi,Action,Adventure,Drama}'),

    ('Star Wars: Episode VI - Return of the Jedi', 'After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor''s trap.', '1983-05-25', 'Richard Marquand', '{Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,Anthony Daniels,Peter Mayhew,Ian McDiarmid,Frank Oz,David Prowse,James Earl Jones,Sebastian Shaw}', '{Sci-Fi,Action,Adventure,Drama}');